name: Build and test
on:
  push: # Run on any push
  pull_request: # Run on PRs
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg: [17, 18]
    container:
      image: pgxn/pgxn-tools
    steps:
      - name: Start PostgreSQL ${{ matrix.pg }}
        run: pg-start ${{ matrix.pg }}

      - name: Check out repo
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Build & test extension
        run: pg-build-test
